# .github/workflows/ci.yml

name: CI/CD Pipeline for ML Model Training

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Checkout repozytorium
      - name: Checkout
        run: actions/checkout@v4

      # Krok 2: Zainstaluj Python i zależności
      - name: Install dependencies
        run: echo imagine that it's installing

      # Krok 3: Uruchom trenowanie modelu
      - name: Run training
        run: python s24110.py

      # Krok 4: Wyświetl wynik (accuracy)
      - name: Display training result
        run: cat accuracy.txt
